// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5UkTUCWjvMb9N_VLsL-1hqf3RWkOxLU',
    appId: '1:99734503652:web:0bbe3bff67b9a3152d6cf1',
    messagingSenderId: '99734503652',
    projectId: 'mental-health-4a855',
    authDomain: 'mental-health-4a855.firebaseapp.com',
    storageBucket: 'mental-health-4a855.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSOiWUjF2xMpioUw6n80myZqjqTVssEtM',
    appId: '1:99734503652:android:32cda8f1cc4f548f2d6cf1',
    messagingSenderId: '99734503652',
    projectId: 'mental-health-4a855',
    storageBucket: 'mental-health-4a855.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ-KxLUBd5lnWTMAfJSkfQM5uQIRuFXxE',
    appId: '1:99734503652:ios:7a4164f15af5cbce2d6cf1',
    messagingSenderId: '99734503652',
    projectId: 'mental-health-4a855',
    storageBucket: 'mental-health-4a855.firebasestorage.app',
    iosBundleId: 'com.s4k1l.mentalhealth',
  );
}
